name: Deploy to Amazon ECS

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: db-server-runner
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Copy Secret yml
        env:
          CREATE_SECRET: ${{secrets.EDUPI_DB_DEV_APPLICATION_YML}}
          CREATE_SECRET_DIR: src/main/resources
          CREATE_SECRET_DIR_FILE_NAME: application.yml
        run: echo $CREATE_SECRET | base64 --decode > $CREATE_SECRET_DIR/$CREATE_SECRET_DIR_FILE_NAME

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build


